#!/bin/bash
# ============================================================
# Google Sheets Setup — 2 options explained
# ============================================================

echo ""
echo "======================================================"
echo "  Google Sheets Setup"
echo "======================================================"
echo ""
echo "OPTION A (Easiest — 5 min) — Google Service Account:"
echo "  This gives n8n permanent write access without browser login."
echo ""
echo "  Steps:"
echo "  1. Go to: https://console.cloud.google.com/projectcreate"
echo "     Name: security-pipeline → Create"
echo ""
echo "  2. Enable Sheets API:"
echo "     https://console.cloud.google.com/apis/library/sheets.googleapis.com"
echo "     → Click Enable"
echo ""
echo "  3. Create Service Account:"
echo "     → IAM & Admin → Service Accounts → Create Service Account"
echo "     → Name: n8n-sheets-writer → Create and continue → Done"
echo ""
echo "  4. Create JSON key:"
echo "     → Click the service account → Keys tab → Add Key → JSON"
echo "     → Download saved to your Downloads folder"
echo "     → Move it: mv ~/Downloads/*.json /home/pavan/security-pipeline/google-sa.json"
echo ""
echo "  5. Create your Google Sheet:"
echo "     → https://sheets.google.com → Blank spreadsheet"
echo "     → Name it: Security Knowledge Base"
echo "     → In Row 1 paste these exact headers in columns A-N:"
echo ""
echo "        A: Date Added"
echo "        B: Title"
echo "        C: Category"
echo "        D: Vulnerability Type"
echo "        E: Severity"
echo "        F: Quality Score"
echo "        G: Tools Used"
echo "        H: Source URL"
echo "        I: Root Cause"
echo "        J: Key Takeaways"
echo "        K: Status"
echo "        L: Obsidian File"
echo "        M: Chaining Potential"
echo "        N: Impact"
echo ""
echo "  6. Share the sheet with your service account email:"
echo "     → Click Share (top right)"
echo "     → Paste the service account email (from google-sa.json → client_email)"
echo "     → Set to Editor → Share"
echo ""
echo "  7. Copy your Sheet ID from the URL:"
echo "     URL: https://docs.google.com/spreadsheets/d/SHEET_ID_HERE/edit"
echo "     → Add it to .env: GOOGLE_SHEETS_ID=your_id"
echo ""
echo "------------------------------------------------------"
echo ""
echo "OPTION B — Manual for now, automate later:"
echo "  Skip Google Sheets entirely for now."
echo "  The pipeline still works 100% — Obsidian gets all articles."
echo "  Google Sheets can be added later when you have 5 minutes."
echo ""
echo "  To skip Sheets: just don't create google-sa.json"
echo "  The workflow detects its absence and writes Obsidian-only."
echo ""

# Check if SA file exists
if [ -f "/home/pavan/security-pipeline/google-sa.json" ]; then
    SA_EMAIL=$(python3 -c "import json; print(json.load(open('/home/pavan/security-pipeline/google-sa.json'))['client_email'])" 2>/dev/null)
    if [ -n "$SA_EMAIL" ]; then
        echo "======================================================"
        echo "  Service account found! Email:"
        echo "  $SA_EMAIL"
        echo "  Share your Google Sheet with this email (Editor access)"
        echo "======================================================"
    fi
fi
